# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf827e2cd4e60a2d4e241a333405ee2336c11e38ff277e951483ddc3150e36ecd1cd5d7a719d9469a459e9769506976565029e6b1b5cb9582d57d49f47a52e8c

test:
  secret_key_base: fc5d8664c32475eba2981a571704bebdbf3dfb88ccb9b1961bfbae6560319895e1a36604d9bd92f3da3563d827c7175502aa8ba949bea291da4e4d92d7b6d745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
